version: "3.7"
services:
  redis:
    image: redis:6.2.3
    container_name: adachi-redis
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./database:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  bot:
    build:
      context: .
    image: adachi-bot:2.2.5
    ports:
      - 80:80
    container_name: adachi-bot
    environment:
      docker: "yes"
    depends_on:
      - redis
    volumes:
      - ./config:/bot/config
      - ./logs:/bot/logs
      - ./src:/bot/src
      - ./package.json:/bot/package.json